const projectData = [
  {
    category: "neog",
    title: "Cartoon Quiz",
    description: `Let's check your knowledge about cartoons`,
    challenge: `I learned about basic js.`,
    language: ["javascript"],
    img: `./asset/img/cartoonquiz.jpg`,
    imgDescription: "lorem ispsum",
    githubCode: "https://github.com/vickydarlinn/CartoonQuiz",
    livePreview:
      "https://replit.com/@vickydarlinn/CartoonQuiz#index.js?embed=1&output=1",
  },
  {
    category: "neog",
    title: "You Know me",
    description: `Do you know about me`,
    challenge: `I learned about basic js.`,
    language: ["javascript"],
    img: `./asset/img/know_me.jpg`,
    imgDescription: "lorem ispsum",
    githubCode: "https://github.com/vickydarlinn/You-know-me-",
    livePreview:
      "https://replit.com/@vickydarlinn/You-know-me#index.js?embed=1&output=1",
  },
  {
    category: "neog",
    title: "Know the Fruit",
    description: `In this project, My program tells you which is this fruit name?`,
    challenge: `In this project I explore react library.`,
    language: ["html", "css", "react"],
    img: `./asset/img/fruits.jpg`,
    imgDescription: "know your fruit",
    githubCode: "https://github.com/vickydarlinn/know-your-fruit",
    livePreview: "https://b6mfx.csb.app/",
  },
  {
    category: "neog",
    title: "Movie recommender",
    description: `In this project, My program tells about the movies?`,
    challenge: `In this project I explore react and learned more about jsx. And learn about the difference about jsx and html.`,
    language: ["html", "css", "react"],
    img: `./asset/img/movie_recommender.jpg`,
    imgDescription: "Movie recommender",
    githubCode: "https://github.com/vickydarlinn/Movie_recommender",
    livePreview: "https://xnx1t.csb.app/",
  },
  {
    category: "neog",
    title: "Profit and loss in stocks",
    description: `In this web app we check How much profit or loss we got in Stock Market`,
    challenge: `In Profit and loss challenge, I learnd about element.style.<cssPropertyName>.`,
    language: ["html", "css", "Javascript"],
    img: `./asset/img/stocks.jpg`,
    imgDescription: "stocks p&l checker",
    githubCode: "https://github.com/vickydarlinn/Stocks-calculator-neog",
    livePreview: "https://stock-calculator-neog.netlify.app/",
  },
  {
    category: "neog",
    title: "Banana Talk",
    description: `In this web app we will translate English language to Banana language.`,
    challenge: `During making this web app I learned about: attaching events to html elements taking user. Taking user input in browser and showing output in browser. I also learned about making network calls to get relevant data & error handling network calls. `,
    language: ["html", "css", "Javascript"],
    img: `./asset/img/miniontalk.png`,
    imgDescription: "Banana Talk",
    githubCode: "https://github.com/vickydarlinn/Banana-talk-neogcamp",
    livePreview: "https://banana-talk-translator-neogcamp.netlify.app/",
  },
  {
    category: "neog",
    title: "Pirate speak translator",
    description: `In this web app we will translate English language to Pirate language.`,
    challenge: `During making this web app I learned again about: attaching events to html elements taking user. Taking user input in browser and showing output in browser. I also learned about making network calls to get relevant data & error handling network calls. `,
    language: ["html", "css", "Javascript"],
    img: `./asset/img/pirate_translator.jpg`,
    imgDescription: "Pirate speak",
    githubCode: "https://github.com/vickydarlinn/pirate-speak-translator",
    livePreview: "https://vicky-pirate-speak-translator.netlify.app/",
  },
  {
    category: "neog",
    title: "Cash Register",
    description: `In this web app, My program has all Indian currencies note. This program help the user by telling how can he/she return the change to the customer with a minimum number of notes?`,
    challenge: `During making this web app I sharped my memory to make logic building `,
    language: ["html", "css", "Javascript"],
    img: `./asset/img/cashRegister.jpg`,
    imgDescription: "Banana Talk",
    githubCode: "https://github.com/vickydarlinn/vicky-cash-register",
    livePreview: "https://my-cash-register-neog.netlify.app/",
  },
  {
    category: "neog",
    title: "Is Your Birthday Lucky",
    description: `In this web app, My prrogram will take users B'day and Natural Number. If sum of digits of birthday is divisible by the lucky number and tell his/her bday is lucky or not`,
    challenge: `During making this web app I learned new array method which is \"replaceAll\" `,
    language: ["html", "css", "Javascript"],
    img: `./asset/img/luckybirthday.png`,
    imgDescription: "Lucky BirthDay",
    githubCode: "https://github.com/vickydarlinn/lucky-birthday-checker",
    livePreview: "https://lucky-birthday-checker-neog.netlify.app/",
  },
  {
    category: "neog",
    title: "Fun with Triangles",
    description: `This is web app to check user's knwoledge about triangles!`,
    challenge: `During making this web app I learned about mahth.random method`,
    language: ["html", "css", "Javascript"],
    img: `./asset/img/funwithtriangle.jpg`,
    imgDescription: "Fun with Triangle",
    githubCode: "https://github.com/vickydarlinn/Triangles-neog",
    livePreview: "https://vicky-triangle-neog.netlify.app/",
  },
  {
    category: "neog",
    title: "Palindrome Birthday",
    description: `In this web app, My program will take user's birth date and check it that birtdate is a palindrome. If, the entered date is not a palindtome, then it will show neasrest palindrome date`,
    challenge: `During making this web app I play with strings and numbers`,
    language: ["html", "css", "Javascript"],
    img: `./asset/img/palindrome.jpg`,
    imgDescription: "Palindrome Birthday Checker",
    githubCode:
      "https://github.com/vickydarlinn/Is-Your-Birthdate-a-Palindrome",
    livePreview: "https://birthday-palindrome-checker-neog.netlify.app/",
  },
];

const batchColor = ["#65c3ba", "#4d648d", "#ff6f69"];
const projectBgColor = ["#f6cd61", "#fe8a71", "#83d0c9", "#f6abb6"];
